name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to print'
        required: true
        type: string
    outputs:
      result:
        description: 'The processed message'
        value: ${{ jobs.print.outputs.result }}

jobs:
  print:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.text }}
    steps:
      - name: Printing message
        id: print-step
        run: echo "Message from caller:${{ inputs.message }}" >> $GITHUB_OUTPUT
