name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to print'
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Printing message
        run: echo "Message from caller: ${{ inputs.message }}"
