name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to print'
        required: true
        type: string
    outputs:
      result:
        description: 'The processed message'
        value: ${{ jobs.print.outputs.result }}

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Printing message
        run: echo "Message from caller:${{ inputs.message }}"
      - name: Save output to file
        run: echo "Message from caller:${{ inputs.message }}" > output.txt
      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.run_id }}-${{ github.job }}-${{ inputs.message }}
          path: output.txt
